### ISSUE TITLE
Issue with trimAl on Windows:

### ISSUE THREAD

**Issue by NoorulemanAbid** [scapella/trimal#101]
Hi, I want to use trimAl on Windows. When I download the trimAl executable for Windows and click on it, I get an error saying that libgcc_s_seh-1.dll is missing. After downloading that file, I get another error for libgcc_s_seh-6.dll. When I download this file, I get an error saying that libthread-1.dll was not found. After downloading that file, I receive an error saying that this application was unable to execute with error code 0xc000007b.

**Comment by nicodr97** [comment]
Hi @NoorulemanAbid,
Are you using the binaries of v1.5 (https://github.com/inab/trimal/releases/download/v1.5.0/trimAl_Windows_x86-64.zip) or are you downloding the source code and compiling it? If you are compiling it, how are you doing that?

**Comment by NoorulemanAbid** [comment]
Hi, I am glad you replied. I downloaded the executable of trimAl for Windows from the assets section of GitHub. However, it gave an error. Then I moved to compile the code mentioned on GitHub. I navigated to the project directory, found the source directory, and ran the make command. It worked well in the MinGW terminal but not in the Command Prompt.

**Comment by nicodr97** [comment]
I think there might be some dependencies which I have to included in the binaries. Could you please tell me which Windows version and CPU architecture are you using?
I will make you know once I update the binaries.

Thank you for your feedback!

**Comment by nicodr97** [comment]
@NoorulemanAbid , I uploaded new Windows binaries. Could you check them and confirm they run OK?

**Comment by NoorulemanAbid** [comment]
> I think there might be some dependencies which I have to included in the binaries. Could you please tell me which Windows version and CPU architecture are you using? I will make you know once I update the binaries.
> 
> Thank you for your feedback!

I use window 11 but same issue I face in windows 10

**Comment by NoorulemanAbid** [comment]
> @NoorulemanAbid , I uploaded new Windows binaries. Could you check them and confirm they run OK?

Yes, now it's working fine. I am thankful to you and your team for resolving the issue.
