### ISSUE TITLE
Unable to install new version

### ISSUE THREAD

**Issue by Ricardo-Mouta** [scapella/trimal#103]
Hello all, I have used trimal througth my masters degree and now starting my phd. Thanks a lot for the software, and I'm excited to use the new version. After downloading the source code, I'm trying to install it, but unfortunately when I use the command "make" in the directory "trimal-1.5.0/source" it delivers me the error message:

g++ -Wall -O2  -c alignment.cpp rwAlignment.cpp autAlignment.cpp
make: g++: No such file or directory
make: *** [makefile:29: alignment.o] Error 127

Am I forgetting something? Or is there a file missing?

**Comment by nicodr97** [comment]
Compiling with "make" sould work. What OS are you using? And what is your g++ version?

**Comment by Ricardo-Mouta** [comment]
Hello!
I'm using Ubuntu 22.04.4 LTS. The version of g++ is 11.4.0. I ran "sudo apt upgrade g++" and now it worked! Thank you very much
