### ISSUE TITLE
Please tag a "Release" so it can be packaged

### ISSUE THREAD

**Issue by tseemann** [scapella/trimal#16]
Ideally, to put trimal in Brew / Linuxbrew we need a tagged release.

Would it be possible to make one using the "Releases" tab?

Even it if is 1.4b that's fine - we just need a .tar.gz to download.

**Comment by scapella** [comment]
Hi @tseemann,

As requested I have tagged the stable version as "release" using v1.4.1 as tag.
Please let me know if you have any problem integrating trimAl into Brew / Linuxbrew.
It seems a pretty nice project.

Cheers!

S

**Comment by tseemann** [comment]
Thank you! 
I've submitted a pull request to the team: https://github.com/Homebrew/homebrew-science/pull/2045
