### ISSUE TITLE
FYI - I have packaged trimAl 1.2 

### ISSUE THREAD

**Issue by tseemann** [scapella/trimal#17]
FYI

https://github.com/tseemann/homebrew-bioinformatics-linux/blob/master/trimal.rb

This will eventually be migrated to full homebrew-science if it can compile on OS X cleanly.

https://github.com/Homebrew/homebrew-science

**Comment by scapella** [comment]
Thanks!

Use trimAl release 1.4.1 which has incorporated additional functionality and solved some minor bugs along the development.

Regarding to OS X, please, let me know if there are problems there. A user reported some issues when compiling trimAl for OS but I haven't been able to reproduce them.

S

**Comment by tseemann** [comment]
The 1.2 was just to my sub-homebrew tap. I have submitted 1.4.1 now to the official repository:

https://github.com/Homebrew/homebrew-science/pull/2045
