### ISSUE TITLE
statal prints nothing - no warning to user

### ISSUE THREAD

**Issue by tseemann** [scapella/trimal#18]
Running ```statal -in file.aln``` runs for a while and prints nothing.

I assume that one of the ```-sc*``` options is needed to get an output.

Can you flag an error if no output option is provided?

**Comment by scapella** [comment]
SHA: ecf80a6fc3327f00b754d39559e35026d8226f03
It solves this issue

**Comment by tseemann** [comment]
Thanks. When you make the next release I'll package it.
