### ISSUE TITLE
Problem using -compareset, -ct, -gt together.

### ISSUE THREAD

**Issue by tomfy** [scapella/trimal#23]
When using -compareset, -ct, and -gt together  (perhaps this is not allowed?) I get an output alignment with some extra garbage to the right of the last legitimate column: 
(sorry I don't know how to get fixed-width font here) . 

For example: 

tomfy@t410:~/trimAl_1.4/dataset$ trimal -compareset fileset1 -ct 0.1 -gt 0.1
 6 46
Sp8          ---GKVIV-YGIVLGTKSDQFSVVWLFPWNGLQIHMMGII
Sp17         FAYTDLLL-IGFLLKTV-ATFGDTWFQLWQGLDLNKMPVF
Sp10         ----AVL--FVIMLGTI-TKFSSEWFFAWLGLEINMMVII
Sp26         AAAAALLTYLGLFLGTDYENFAAAAANAWLGLEINMMAQI
Sp33         ----TILNIAGLHMETD-INFSLAWFQAWGGLEINKQAIL
Sp6          ---AAILT-LGIYLFTLCAVISVSWYLAWLGLEINMMAIINKMPVF

tomfy@t410:~/trimAl_1.4/dataset$ trimal -compareset fileset1 -ct 0.2 -gt 0.5
 6 38
Sp8          GIVLGTKSFSVVWLFPWNGLQIHMMGIIQAIL
Sp17         GFLLKTV-FGDTWFQLWQGLDLNKMPVFMAQI
Sp10         VIMLGTI-FSSEWFFAWLGLEINMMVIIMVII
Sp26         GLFLGTDYFAAAAANAWLGLEINMMAQIMPVF
Sp33         GLHMETD-FSLAWFQAWGGLEINKQAILMGII
Sp6          GIYLFTLCISVSWYLAWLGLEINMMAII

**Comment by tomfy** [comment]
My apologies. I was running v 1.2 when I observed this problem. It seems to be fixed in 1.4,
at least I haven't been able to reproduce the problem with 1.4.

**Comment by scapella** [comment]
Dear Thomas,

Thanks for reporting this - and glad to hear I fixed it on v1.4.

If you experience further troubles and want to see specific methods
implemented in trimAl,
please contact me by email.

Cheers,

S

On Tue, Oct 27, 2015 at 7:27 PM, Thomas Fisher-York <
notifications@github.com> wrote:

> My apologies. I was running v 1.2 when I observed this problem. It seems
> to be fixed in 1.4,
> at least I haven't been able to reproduce the problem with 1.4.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scapella/trimal/issues/23#issuecomment-151601382>.
>



-- 
Salva
