### ISSUE TITLE
Error message on some alignments

### ISSUE THREAD

**Issue by m-angelov** [scapella/trimal#25]
Hello!
On some alignment files I get multiple errors, along the line of:
'Error: the symbol 'R' accesing the matrix is not defined in this object' (the symbol is changing).

The thing is, that my sequences are DNA, but as far as I've seen in the code, the default similarity matrix is for proteins. I have tested about 10 MSAs (which are from very similar sources), and some work, some produce the error. On some files statal -ssc gives those errors, but trimal works as expected.

Do you have some hints how could this be resolved?

Thanks!

**Comment by scapella** [comment]
Hi there,

Thanks for using trimAl.
My initial hint would be you are using degenerate codes in some of your DNA
alignments.
You can force statal to use a specific similarity matrix with the -matrix
parameter.

An example of degenerated DNA codes is available here - or at the dataset
folder from trimAl's source code.
https://github.com/scapella/trimal/blob/trimAl/dataset/matrix.degenerated_dna


Said that, you can always give your own matrix with customize values.

Hope this helps to solve your problem,
Cheers,

S

On Tue, Apr 12, 2016 at 11:06 PM, m-angelov <notifications@github.com>
wrote:

> Hello!
> On some alignment files I get multiple errors, along the line of:
> 'Error: the symbol 'R' accesing the matrix is not defined in this object'
> (the symbol is changing).
>
> The thing is, that my sequences are DNA, but as far as I've seen in the
> code, the default similarity matrix is for proteins. I have tested about 10
> MSAs (which are from very similar sources), and some work, some produce the
> error. On some files statal -ssc gives those errors, but trimal works as
> expected.
>
> Do you have some hints how could this be resolved?
>
> Thanks!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/scapella/trimal/issues/25>
>



-- 
Salva

**Comment by m-angelov** [comment]
Ugh, that's what you get when you work with data from other people: "Yeah, it's all fine, no ambiguities" :) Should've checked first.

Thank you for the quick response and the handy software!
