### ISSUE TITLE
Can't install trimal on Mac

### ISSUE THREAD

**Issue by kuhaudos** [scapella/trimal#27]
Hi there,

I just downloaded the trimal v.1.2 for Mac and try to manually install by following the instruction on readme file but it doesn't work. Also, I couldn't find a bin directory in the downloaded folder. Could you please help me with this issue?

Thanks

**Comment by scapella** [comment]
Hi there,

I suggest you to download the developmental version which includes a specific Makefile for MacOS.
Here it is the link - [https://github.com/scapella/trimal/tree/dev] - You just need to substitute the standard makefile (at the **source** folder) by the one named makefile makefile.MacOS at the same folder. Then you can compile it. It should do it smoothly.

Cheers,

S

**Comment by kuhaudos** [comment]
Hi again,

Thank you for the suggestion. I have tried what you suggested and got the below response on Terminal: 

Invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

What have I done wrong here?

**Comment by scapella** [comment]
Hi there,

I'm not an MacOS user - however, I found these two entries with potential
solutions to your problems. Just give a go and try to compile again trimAl.

http://apple.stackexchange.com/questions/209624/how-to-fix-homebrew-error-invalid-active-developer-path-after-upgrade-to-os-x

https://ohthehugemanatee.org/blog/2015/10/01/how-i-got-el-capitain-working-with-my-developer-tools/

Cheers,

S

Salva
