### ISSUE TITLE
ERROR: Alignment not loaded:

### ISSUE THREAD

**Issue by xiaoaozqd** [scapella/trimal#36]
Dear,
When I trim the output CLUSTAL file by muscle(3.8)  with trimAl (v1.4.rev22),  all the Symbol become the filrst one. could you give me some suggestion?
code
` trimal -in region_muscle.clw -out region_muscle_trimal_auto -automated1`

my email:
[region_muscle.txt](https://github.com/scapella/trimal/files/1361475/region_muscle.txt)

zqdong@nwsuaf.edu.cn

**Comment by scapella** [comment]
dear @xiaoaozqd 

We have implemented a small fix for your potential error. However, your file example is truncated.
Please, download the latest version and check it with a non-truncated version of your file. 

Cheers,
S
