### ISSUE TITLE
Should gaps be included in the conservation score computation?

### ISSUE THREAD

**Issue by thkuo** [scapella/trimal#37]
Dear developers,
Can it be better that the blosum matrix in this package (matrix.BLOSUM62) contains one more state for gaps (ie. '-'). When I tried to remove fully conserved columns, the result was expected to exclude monotonic columns, such as:
```
A
A
A
A
A
```
However, a column like
```
A
-
A
A
A
```
also had a 1.0 conservation score, computed by -scc function, although it was not fully conserved. It seems not so straightforward to specifically detect the first case with -gt and -st. Can there be any suggestion for people trying to remove monotonic columns (ie. containing single residue type and without gaps)?

**Comment by scapella** [comment]
@thkuo 

You can use a combination of parameters to get exactly what you are looking for.

If you use `-st 1`, you will get as output all columns with identical residues including some of them with gaps. If you include `-st 1 -gt 1` then you will get only columns with identical residues without any gaps.

Finally, if you do `-st 1 -gt 1 -complementary` you will remove identical columns without gaps, which to my understanding is what you are looking for.

**Comment by thkuo** [comment]
Many thanks!
