### ISSUE TITLE
Compilation problem (mac os 10.13, Kernel Version: Darwin 17.0.0)

### ISSUE THREAD

**Issue by dinhe878** [scapella/trimal#38]
Hi,

I tried to compile both v1.2 & v1.4. Below are the error messages.
########
g++ -Wall  -c compareFiles.cpp
g++: warning: couldn’t understand kern.osversion ‘17.0.0
In file included from /usr/include/Availability.h:194:0,
                 from /usr/include/stdlib.h:61,
                 from compareFiles.h:30,
                 from compareFiles.cpp:27:
/usr/include/AvailabilityInternal.h:25584:74: error: missing binary operator before token "("
 #if defined(__has_feature) && defined(__has_attribute) && __has_attribute(availability)
                                                                          ^
In file included from /usr/include/stdlib.h:61:0,
                 from compareFiles.h:30,
                 from compareFiles.cpp:27:
/usr/include/Availability.h:387:74: error: missing binary operator before token "("
 #if defined(__has_feature) && defined(__has_attribute) && __has_attribute(availability)
                                                                          ^
make: *** [compareFiles.o] Error 1

**Comment by scapella** [comment]
@dinhe878

Have you tried to compile the latest stable trimAl version using the makefile for MacOS system?
You can use the specific makefile for MacOS by typing the following at the source code folder. It allows you to use a specific file as makefile rather than the generic one.

`makefile -f makefile.MacOS`

**Comment by dinhe878** [comment]
Thanks @scapella, I tried but it didn't work. Below are the error messages.
########
source ding$ make -f makefile.MacOS

g++ -Wall  -c alignment.cpp rwAlignment.cpp autAlignment.cpp
g++: warning: couldn’t understand kern.osversion ‘17.0.0
g++ -Wall  -c statisticsGaps.cpp
g++: warning: couldn’t understand kern.osversion ‘17.0.0
g++ -Wall  -c utils.cpp
g++: warning: couldn’t understand kern.osversion ‘17.0.0
g++ -Wall  -c similarityMatrix.cpp
g++: warning: couldn’t understand kern.osversion ‘17.0.0
g++ -Wall  -c statisticsConservation.cpp
g++: warning: couldn’t understand kern.osversion ‘17.0.0
g++ -Wall  -c sequencesMatrix.cpp
g++: warning: couldn’t understand kern.osversion ‘17.0.0
g++ -Wall  -c compareFiles.cpp
g++: warning: couldn’t understand kern.osversion ‘17.0.0
In file included from /usr/include/Availability.h:194:0,
                 from /usr/include/stdlib.h:61,
                 from compareFiles.h:30,
                 from compareFiles.cpp:27:
/usr/include/AvailabilityInternal.h:25584:74: error: missing binary operator before token "("
 #if defined(__has_feature) && defined(__has_attribute) && __has_attribute(availability)
                                                                          ^
In file included from /usr/include/stdlib.h:61:0,
                 from compareFiles.h:30,
                 from compareFiles.cpp:27:
/usr/include/Availability.h:387:74: error: missing binary operator before token "("
 #if defined(__has_feature) && defined(__has_attribute) && __has_attribute(availability)
                                                                          ^
make: *** [compareFiles.o] Error 1

**Comment by scapella** [comment]
@dinhe878 

Please, have a look at this post where a similar issue was raised and solved.
https://stackoverflow.com/questions/26486163/gcc-4-9-1-in-os-x-yosemite-gcc-warning-couldn-t-understand-kern-osversion-1

Please, let us know if you managed to solve it

**Comment by scapella** [comment]
@dinhe878 

Please, have a look at this post where a similar issue was raised and solved.
https://stackoverflow.com/questions/26486163/gcc-4-9-1-in-os-x-yosemite-gcc-warning-couldn-t-understand-kern-osversion-1

Please, let us know if you manage to solve it.

**Comment by dinhe878** [comment]
Hi @scapella 

I've tried all the suggestions from that post and had no luck. I also tried to use the system compiler (/Applications//Xcode.app/Contents/Developer/usr/bin/g++) since I realised that before it used /anaconda2/bin/g++. But still, not working...

### My clang info ###
Apple LLVM version 8.1.0 (clang-802.0.38)
Target: x86_64-apple-darwin17.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
#################

Here are the (new) error messages:
/Applications//Xcode.app/Contents/Developer/usr/bin/g++ -Wall  -o readal readAl.cpp -lm alignment.o statisticsGaps.o utils.o similarityMatrix.o statisticsConservation.o sequencesMatrix.o compareFiles.o
Undefined symbols for architecture x86_64:
  "alignment::getSequences(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*)", referenced from:
      compareFiles::algorithm(alignment**, char**, float*, int, bool) in compareFiles.o
      compareFiles::forceComparison(alignment**, int, alignment*, float*) in compareFiles.o
  "alignment::getSeqNameOrder(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, int*)", referenced from:
      compareFiles::algorithm(alignment**, char**, float*, int, bool) in compareFiles.o
      compareFiles::forceComparison(alignment**, int, alignment*, float*) in compareFiles.o
  "alignment::printAlignmentInfo(std::__1::basic_ostream<char, std::__1::char_traits<char> >&)", referenced from:
      _main in readAl-a0e1cd.o
  "std::string::find_last_not_of(char const*, unsigned long) const", referenced from:
      alignment::checkCorrespondence(std::string*, int*, int, int) in alignment.o
  "std::string::data() const", referenced from:
      __ZSteqIcEN9__gnu_cxx11__enable_ifIXsrSt9__is_charIT_E7__valueEbE6__typeERKSbIS3_St11char_traitsIS3_ESaIS3_EESC_ in alignment.o
  "std::string::find(char const*, unsigned long) const", referenced from:
      alignment::alignmentNexusToFile(std::ostream&) in alignment.o
      alignment::prepareCodingSequence(bool, bool, alignment*) in alignment.o
      utils::readLine(std::basic_ifstream<char, std::char_traits<char> >&) in utils.o
      utils::trimLine(std::string) in utils.o
      utils::readNumbers_StartEnd(std::string) in utils.o
      utils::readNumbers(std::string) in utils.o
  "std::string::find(char, unsigned long) const", referenced from:
      alignment::calculateColIdentity(float*) in alignment.o
      utils::removeCharacter(char, std::string) in utils.o
  "std::string::size() const", referenced from:
      alignment::fillMatrices(bool) in alignment.o
      alignment::getSequences(std::ostream&) in alignment.o
      alignment::loadPhylip3_2Alignment(char*) in alignment.o
      alignment::loadNBRF_PirAlignment(char*) in alignment.o
      alignment::alignmentPhylipToFile(std::ostream&) in alignment.o
      alignment::alignmentPhylip3_2ToFile(std::ostream&) in alignment.o
      alignment::alignmentPhylip_PamlToFile(std::ostream&) in alignment.o
      ...
  "std::string::c_str() const", referenced from:
      utils::readLine(std::basic_ifstream<char, std::char_traits<char> >&) in utils.o
      utils::trimLine(std::string) in utils.o
      utils::readNumbers_StartEnd(std::string) in utils.o
      utils::readNumbers(std::string) in utils.o
  "std::string::empty() const", referenced from:
      alignment::calculateColIdentity(float*) in alignment.o
  "std::string::rfind(char const*, unsigned long) const", referenced from:
      utils::trimLine(std::string) in utils.o
  "std::string::length() const", referenced from:
      alignment::getTranslationCDS(int, int, int*, std::string*, sequencesMatrix*, alignment*) in alignment.o
      alignment::getSequences(std::string*, int*) in alignment.o
      alignment::getSequences(std::string*, std::string*, int*) in alignment.o
      alignment::prepareCodingSequence(bool, bool, alignment*) in alignment.o
      alignment::checkCorrespondence(std::string*, int*, int, int) in alignment.o
  "std::string::substr(unsigned long, unsigned long) const", referenced from:
      alignment::getSequences(std::ostream&) in alignment.o
      alignment::alignmentPhylipToFile(std::ostream&) in alignment.o
      alignment::alignmentPhylip3_2ToFile(std::ostream&) in alignment.o
      alignment::alignmentPhylip_PamlToFile(std::ostream&) in alignment.o
      alignment::alignmentClustalToFile(std::ostream&) in alignment.o
      alignment::alignmentFastaToFile(std::ostream&) in alignment.o
      alignment::alignmentNexusToFile(std::ostream&) in alignment.o
      ...
  "std::string::compare(std::string const&) const", referenced from:
      alignment::getTranslationCDS(int, int, int*, std::string*, sequencesMatrix*, alignment*) in alignment.o
      sequencesMatrix::getSequence(std::string, int*) in sequencesMatrix.o
  "std::string::compare(unsigned long, unsigned long, char const*) const", referenced from:
      alignment::alignmentNexusToFile(std::ostream&) in alignment.o
  "std::basic_ios<char, std::char_traits<char> >::eof() const", referenced from:
      alignment::formatInputAlignment(char*) in alignment.o
      alignment::loadPhylipAlignment(char*) in alignment.o
      alignment::loadPhylip3_2Alignment(char*) in alignment.o
      alignment::loadClustalAlignment(char*) in alignment.o
      alignment::loadFastaAlignment(char*) in alignment.o
      alignment::loadNexusAlignment(char*) in alignment.o
      alignment::loadMegaNonInterleavedAlignment(char*) in alignment.o
      ...
  "std::basic_ios<char, std::char_traits<char> >::fail() const", referenced from:
      similarityMatrix::loadSimMatrix(char*) in similarityMatrix.o
  "std::basic_ios<char, std::char_traits<char> >::operator!() const", referenced from:
      alignment::alignmentSummaryHTML(char*, int, int, int*, int*, float*) in alignment.o
      alignment::saveAlignment(char*) in alignment.o
      utils::checkFile(std::basic_ifstream<char, std::char_traits<char> >&) in utils.o
  "std::allocator<char>::allocator()", referenced from:
      alignment::loadMegaNonInterleavedAlignment(char*) in alignment.o
      alignment::loadMegaInterleavedAlignment(char*) in alignment.o
      alignment::getTranslationCDS(int, int, int*, std::string*, sequencesMatrix*, alignment*) in alignment.o
      utils::determineColor(char, std::string) in utils.o
  "std::allocator<char>::~allocator()", referenced from:
      alignment::loadMegaNonInterleavedAlignment(char*) in alignment.o
      alignment::loadMegaInterleavedAlignment(char*) in alignment.o
      alignment::getTranslationCDS(int, int, int*, std::string*, sequencesMatrix*, alignment*) in alignment.o
      utils::determineColor(char, std::string) in utils.o
  "std::istream::read(char*, long)", referenced from:
      alignment::formatInputAlignment(char*) in alignment.o
      utils::readLine(std::basic_ifstream<char, std::char_traits<char> >&) in utils.o
  "std::istream::seekg(std::fpos<__mbstate_t>)", referenced from:
      alignment::loadClustalAlignment(char*) in alignment.o
      alignment::loadFastaAlignment(char*) in alignment.o
      alignment::loadMegaNonInterleavedAlignment(char*) in alignment.o
      alignment::loadMegaInterleavedAlignment(char*) in alignment.o
      alignment::loadNBRF_PirAlignment(char*) in alignment.o
  "std::istream::seekg(long long, std::_Ios_Seekdir)", referenced from:
      utils::checkFile(std::basic_ifstream<char, std::char_traits<char> >&) in utils.o
  "std::istream::tellg()", referenced from:
      utils::checkFile(std::basic_ifstream<char, std::char_traits<char> >&) in utils.o
  "std::istream::getline(char*, long)", referenced from:
      similarityMatrix::loadSimMatrix(char*) in similarityMatrix.o
  "std::istream::operator>>(float&)", referenced from:
      similarityMatrix::loadSimMatrix(char*) in similarityMatrix.o
  "std::ostream::operator<<(std::ostream& (*)(std::ostream&))", referenced from:
      alignment::fillMatrices(bool) in alignment.o
      alignment::getSequences(std::ostream&) in alignment.o
      alignment::alignmentPhylipToFile(std::ostream&) in alignment.o
      alignment::alignmentPhylip3_2ToFile(std::ostream&) in alignment.o
      alignment::alignmentPhylip_PamlToFile(std::ostream&) in alignment.o
      alignment::alignmentClustalToFile(std::ostream&) in alignment.o
      alignment::alignmentFastaToFile(std::ostream&) in alignment.o
      ...
  "std::ostream::operator<<(std::ios_base& (*)(std::ios_base&))", referenced from:
      alignment::alignmentPhylipToFile(std::ostream&) in alignment.o
      alignment::alignmentPhylip3_2ToFile(std::ostream&) in alignment.o
      alignment::alignmentPhylip_PamlToFile(std::ostream&) in alignment.o
      alignment::alignmentClustalToFile(std::ostream&) in alignment.o
      alignment::alignmentNexusToFile(std::ostream&) in alignment.o
      alignment::alignmentSummaryHTML(char*, int, int, int*, int*, float*) in alignment.o
      alignment::alignmentColourHTML(std::ostream&) in alignment.o
      ...
  "std::ostream::operator<<(double)", referenced from:
      alignment::printSeqIdentity() in alignment.o
      statisticsGaps::printGapsColumns() in statisticsGaps.o
      statisticsGaps::printGapsAcl() in statisticsGaps.o
      statisticsConservation::printConservationAcl() in statisticsConservation.o
  "std::ostream::operator<<(float)", referenced from:
      alignment::printAlignmentInfo(std::ostream&) in alignment.o
      alignment::printSeqIdentity() in alignment.o
      alignment::printSeqOverlap() in alignment.o
      alignment::printColumnsIdentity_DescriptiveStats() in alignment.o
      similarityMatrix::printMatrix() in similarityMatrix.o
      statisticsConservation::printConservationColumns() in statisticsConservation.o
      statisticsConservation::printConservationAcl() in statisticsConservation.o
      ...
  "std::ostream::operator<<(int)", referenced from:
      alignment::fillMatrices(bool) in alignment.o
      alignment::alignmentPhylipToFile(std::ostream&) in alignment.o
      alignment::alignmentPhylip3_2ToFile(std::ostream&) in alignment.o
      alignment::alignmentPhylip_PamlToFile(std::ostream&) in alignment.o
      alignment::alignmentNexusToFile(std::ostream&) in alignment.o
      alignment::alignmentMegaToFile(std::ostream&) in alignment.o
      alignment::alignmentNBRF_PirToFile(std::ostream&) in alignment.o
      ...
  "std::ostream::operator<<(unsigned long)", referenced from:
      alignment::prepareCodingSequence(bool, bool, alignment*) in alignment.o
  "std::string::clear()", referenced from:
      alignment::loadPhylip3_2Alignment(char*) in alignment.o
      alignment::loadMegaNonInterleavedAlignment(char*) in alignment.o
      alignment::loadMegaInterleavedAlignment(char*) in alignment.o
      alignment::alignmentSummaryHTML(char*, int, int, int*, int*, float*) in alignment.o
      alignment::alignmentColourHTML(std::ostream&) in alignment.o
      alignment::calculateColIdentity(float*) in alignment.o
      alignment::~alignment() in alignment.o
      ...
  "std::string::erase(unsigned long, unsigned long)", referenced from:
      alignment::loadNBRF_PirAlignment(char*) in alignment.o
      alignment::alignmentNexusToFile(std::ostream&) in alignment.o
      alignment::calculateColIdentity(float*) in alignment.o
      utils::readLine(std::basic_ifstream<char, std::char_traits<char> >&) in utils.o
      utils::trimLine(std::string) in utils.o
      utils::removeCharacter(char, std::string) in utils.o
  "std::string::append(char const*)", referenced from:
      alignment::loadPhylipAlignment(char*) in alignment.o
      alignment::loadPhylip3_2Alignment(char*) in alignment.o
      alignment::loadClustalAlignment(char*) in alignment.o
      alignment::loadFastaAlignment(char*) in alignment.o
      alignment::loadNexusAlignment(char*) in alignment.o
      alignment::loadMegaNonInterleavedAlignment(char*) in alignment.o
      alignment::loadMegaInterleavedAlignment(char*) in alignment.o
      ...
  "std::string::append(char const*, unsigned long)", referenced from:
      alignment::loadPhylipAlignment(char*) in alignment.o
      alignment::loadPhylip3_2Alignment(char*) in alignment.o
      alignment::loadClustalAlignment(char*) in alignment.o
      alignment::loadFastaAlignment(char*) in alignment.o
      alignment::loadNexusAlignment(char*) in alignment.o
      alignment::loadMegaNonInterleavedAlignment(char*) in alignment.o
      alignment::loadMegaInterleavedAlignment(char*) in alignment.o
      ...
  "std::string::append(std::string const&)", referenced from:
      alignment::loadPhylip3_2Alignment(char*) in alignment.o
  "std::string::resize(unsigned long)", referenced from:
      alignment::prepareCodingSequence(bool, bool, alignment*) in alignment.o
  "std::string::resize(unsigned long, char)", referenced from:
      alignment::getTranslationCDS(int, int, int*, std::string*, sequencesMatrix*, alignment*) in alignment.o
      alignment::fillNewDataStructure(std::string*, std::string*) in alignment.o
      alignment::fillNewDataStructure(newValues*) in alignment.o
      utils::readLine(std::basic_ifstream<char, std::char_traits<char> >&) in utils.o
  "std::string::reserve(unsigned long)", referenced from:
      alignment::alignmentSummaryHTML(char*, int, int, int*, int*, float*) in alignment.o
      alignment::alignmentColourHTML(std::ostream&) in alignment.o
  "std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)", referenced from:
      alignment::loadMegaNonInterleavedAlignment(char*) in alignment.o
      alignment::loadMegaInterleavedAlignment(char*) in alignment.o
      alignment::getTranslationCDS(int, int, int*, std::string*, sequencesMatrix*, alignment*) in alignment.o
      utils::determineColor(char, std::string) in utils.o
  "std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&)", referenced from:
      alignment::getSequences(std::ostream&) in alignment.o
      alignment::alignmentPhylipToFile(std::ostream&) in alignment.o
      alignment::alignmentPhylip3_2ToFile(std::ostream&) in alignment.o
      alignment::alignmentPhylip_PamlToFile(std::ostream&) in alignment.o
      alignment::alignmentClustalToFile(std::ostream&) in alignment.o
      alignment::alignmentFastaToFile(std::ostream&) in alignment.o
      alignment::alignmentNexusToFile(std::ostream&) in alignment.o
      ...
  "std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string()", referenced from:
      alignment::getSequences(std::ostream&) in alignment.o
      alignment::formatInputAlignment(char*) in alignment.o
      alignment::loadPhylipAlignment(char*) in alignment.o
      alignment::loadPhylip3_2Alignment(char*) in alignment.o
      alignment::loadClustalAlignment(char*) in alignment.o
      alignment::loadFastaAlignment(char*) in alignment.o
      alignment::loadNexusAlignment(char*) in alignment.o
      ...
  "std::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()", referenced from:
      alignment::getSequences(std::ostream&) in alignment.o
      alignment::formatInputAlignment(char*) in alignment.o
      alignment::loadPhylipAlignment(char*) in alignment.o
      alignment::loadPhylip3_2Alignment(char*) in alignment.o
      alignment::loadClustalAlignment(char*) in alignment.o
      alignment::loadFastaAlignment(char*) in alignment.o
      alignment::loadNexusAlignment(char*) in alignment.o
      ...
  "std::string::operator=(char const*)", referenced from:
      alignment::alignmentNBRF_PirToFile(std::ostream&) in alignment.o
      alignment::alignment() in alignment.o
      alignment::alignment() in alignment.o
      alignment::alignment(std::string, std::string, std::string*, std::string*, std::string*, int, int, int, int, bool, int, int, bool, bool, int, int, bool, bool, int, int, int*, int*, int*, int, int, int, float**, float**) in alignment.o
      alignment::alignment(std::string, std::string, std::string*, std::string*, std::string*, int, int, int, int, bool, int, int, bool, bool, int, int, bool, bool, int, int, int*, int*, int*, int, int, int, float**, float**) in alignment.o
  "std::string::operator=(std::string const&)", referenced from:
      alignment::getSequences(std::ostream&) in alignment.o
      alignment::alignmentPhylipToFile(std::ostream&) in alignment.o
      alignment::alignmentPhylip3_2ToFile(std::ostream&) in alignment.o
      alignment::alignmentPhylip_PamlToFile(std::ostream&) in alignment.o
      alignment::alignmentClustalToFile(std::ostream&) in alignment.o
      alignment::alignmentFastaToFile(std::ostream&) in alignment.o
      alignment::alignmentNexusToFile(std::ostream&) in alignment.o
      ...
  "std::string::operator[](unsigned long)", referenced from:
      alignment::fillMatrices(bool) in alignment.o
      alignment::loadNBRF_PirAlignment(char*) in alignment.o
      alignment::alignmentSummaryHTML(char*, int, int, int*, int*, float*) in alignment.o
      alignment::alignmentColourHTML(std::ostream&) in alignment.o
      alignment::printAlignmentInfo(std::ostream&) in alignment.o
      alignment::calculateSeqIdentity() in alignment.o
      alignment::calculateSeqOverlap() in alignment.o
      ...
  "std::string::operator+=(char const*)", referenced from:
      alignment::loadMegaNonInterleavedAlignment(char*) in alignment.o
      alignment::loadMegaInterleavedAlignment(char*) in alignment.o
  "std::string::operator+=(char)", referenced from:
      alignment::alignmentSummaryHTML(char*, int, int, int*, int*, float*) in alignment.o
      alignment::alignmentColourHTML(std::ostream&) in alignment.o
      alignment::calculateColIdentity(float*) in alignment.o
      utils::getReverse(std::string) in utils.o
  "std::basic_ifstream<char, std::char_traits<char> >::open(char const*, std::_Ios_Openmode)", referenced from:
      alignment::formatInputAlignment(char*) in alignment.o
      alignment::loadPhylipAlignment(char*) in alignment.o
      alignment::loadPhylip3_2Alignment(char*) in alignment.o
      alignment::loadClustalAlignment(char*) in alignment.o
      alignment::loadFastaAlignment(char*) in alignment.o
      alignment::loadNexusAlignment(char*) in alignment.o
      alignment::loadMegaNonInterleavedAlignment(char*) in alignment.o
      ...
  "std::basic_ifstream<char, std::char_traits<char> >::close()", referenced from:
      alignment::formatInputAlignment(char*) in alignment.o
      alignment::loadPhylipAlignment(char*) in alignment.o
      alignment::loadPhylip3_2Alignment(char*) in alignment.o
      alignment::loadClustalAlignment(char*) in alignment.o
      alignment::loadFastaAlignment(char*) in alignment.o
      alignment::loadNexusAlignment(char*) in alignment.o
      alignment::loadMegaNonInterleavedAlignment(char*) in alignment.o
      ...
  "std::basic_ifstream<char, std::char_traits<char> >::basic_ifstream()", referenced from:
      alignment::formatInputAlignment(char*) in alignment.o
      alignment::loadPhylipAlignment(char*) in alignment.o
      alignment::loadPhylip3_2Alignment(char*) in alignment.o
      alignment::loadClustalAlignment(char*) in alignment.o
      alignment::loadFastaAlignment(char*) in alignment.o
      alignment::loadNexusAlignment(char*) in alignment.o
      alignment::loadMegaNonInterleavedAlignment(char*) in alignment.o
      ...
  "std::basic_ifstream<char, std::char_traits<char> >::~basic_ifstream()", referenced from:
      alignment::formatInputAlignment(char*) in alignment.o
      alignment::loadPhylipAlignment(char*) in alignment.o
      alignment::loadPhylip3_2Alignment(char*) in alignment.o
      alignment::loadClustalAlignment(char*) in alignment.o
      alignment::loadFastaAlignment(char*) in alignment.o
      alignment::loadNexusAlignment(char*) in alignment.o
      alignment::loadMegaNonInterleavedAlignment(char*) in alignment.o
      ...
  "std::basic_ofstream<char, std::char_traits<char> >::open(char const*, std::_Ios_Openmode)", referenced from:
      alignment::alignmentSummaryHTML(char*, int, int, int*, int*, float*) in alignment.o
      alignment::saveAlignment(char*) in alignment.o
  "std::basic_ofstream<char, std::char_traits<char> >::close()", referenced from:
      alignment::alignmentSummaryHTML(char*, int, int, int*, int*, float*) in alignment.o
      alignment::saveAlignment(char*) in alignment.o
  "std::basic_ofstream<char, std::char_traits<char> >::basic_ofstream()", referenced from:
      alignment::alignmentSummaryHTML(char*, int, int, int*, int*, float*) in alignment.o
      alignment::saveAlignment(char*) in alignment.o
  "std::basic_ofstream<char, std::char_traits<char> >::~basic_ofstream()", referenced from:
      alignment::alignmentSummaryHTML(char*, int, int, int*, int*, float*) in alignment.o
      alignment::saveAlignment(char*) in alignment.o
  "std::ios_base::Init::Init()", referenced from:
      __static_initialization_and_destruction_0(int, int) in alignment.o
      __static_initialization_and_destruction_0(int, int) in statisticsGaps.o
      __static_initialization_and_destruction_0(int, int) in utils.o
      __static_initialization_and_destruction_0(int, int) in similarityMatrix.o
      __static_initialization_and_destruction_0(int, int) in statisticsConservation.o
      __static_initialization_and_destruction_0(int, int) in sequencesMatrix.o
  "std::ios_base::Init::~Init()", referenced from:
      __static_initialization_and_destruction_0(int, int) in alignment.o
      __static_initialization_and_destruction_0(int, int) in statisticsGaps.o
      __static_initialization_and_destruction_0(int, int) in utils.o
      __static_initialization_and_destruction_0(int, int) in similarityMatrix.o
      __static_initialization_and_destruction_0(int, int) in statisticsConservation.o
      __static_initialization_and_destruction_0(int, int) in sequencesMatrix.o
  "std::basic_ios<char, std::char_traits<char> >::clear(std::_Ios_Iostate)", referenced from:
      alignment::loadClustalAlignment(char*) in alignment.o
      alignment::loadFastaAlignment(char*) in alignment.o
      alignment::loadMegaNonInterleavedAlignment(char*) in alignment.o
      alignment::loadMegaInterleavedAlignment(char*) in alignment.o
      alignment::loadNBRF_PirAlignment(char*) in alignment.o
  "std::cerr", referenced from:
      alignment::fillMatrices(bool) in alignment.o
      alignment::alignmentPhylipToFile(std::ostream&) in alignment.o
      alignment::alignmentPhylip3_2ToFile(std::ostream&) in alignment.o
      alignment::alignmentPhylip_PamlToFile(std::ostream&) in alignment.o
      alignment::alignmentClustalToFile(std::ostream&) in alignment.o
      alignment::alignmentFastaToFile(std::ostream&) in alignment.o
      alignment::alignmentNexusToFile(std::ostream&) in alignment.o
      ...
  "std::cout", referenced from:
      alignment::printSeqIdentity() in alignment.o
      alignment::printSeqOverlap() in alignment.o
      alignment::printColumnsIdentity_DescriptiveStats() in alignment.o
      alignment::printAlignment() in alignment.o
      alignment::printCorrespondence() in alignment.o
      statisticsGaps::printGapsColumns() in statisticsGaps.o
      statisticsGaps::printGapsAcl() in statisticsGaps.o
      ...
  "std::basic_ostream<char, std::char_traits<char> >& std::endl<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&)", referenced from:
      alignment::fillMatrices(bool) in alignment.o
      alignment::getSequences(std::ostream&) in alignment.o
      alignment::alignmentPhylipToFile(std::ostream&) in alignment.o
      alignment::alignmentPhylip3_2ToFile(std::ostream&) in alignment.o
      alignment::alignmentPhylip_PamlToFile(std::ostream&) in alignment.o
      alignment::alignmentClustalToFile(std::ostream&) in alignment.o
      alignment::alignmentFastaToFile(std::ostream&) in alignment.o
      ...
  "std::basic_ostream<char, std::char_traits<char> >& std::operator<<<std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*)", referenced from:
      alignment::fillMatrices(bool) in alignment.o
      alignment::getSequences(std::ostream&) in alignment.o
      alignment::alignmentPhylipToFile(std::ostream&) in alignment.o
      alignment::alignmentPhylip3_2ToFile(std::ostream&) in alignment.o
      alignment::alignmentPhylip_PamlToFile(std::ostream&) in alignment.o
      alignment::alignmentClustalToFile(std::ostream&) in alignment.o
      alignment::alignmentFastaToFile(std::ostream&) in alignment.o
      ...
  "std::basic_ostream<char, std::char_traits<char> >& std::operator<<<std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char)", referenced from:
      alignment::fillMatrices(bool) in alignment.o
      alignment::alignmentSummaryHTML(char*, int, int, int*, int*, float*) in alignment.o
      alignment::alignmentColourHTML(std::ostream&) in alignment.o
      alignment::prepareCodingSequence(bool, bool, alignment*) in alignment.o
      similarityMatrix::getDistance(char, char) in similarityMatrix.o
  "std::basic_ostream<char, std::char_traits<char> >& std::operator<<<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, std::_Setiosflags)", referenced from:
      alignment::printSeqIdentity() in alignment.o
      alignment::printSeqOverlap() in alignment.o
      statisticsGaps::printGapsAcl() in statisticsGaps.o
  "std::basic_ostream<char, std::char_traits<char> >& std::operator<<<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, std::_Setprecision)", referenced from:
      similarityMatrix::printMatrix() in similarityMatrix.o
  "std::basic_ostream<char, std::char_traits<char> >& std::operator<<<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, std::_Setw)", referenced from:
      alignment::alignmentPhylipToFile(std::ostream&) in alignment.o
      alignment::alignmentPhylip3_2ToFile(std::ostream&) in alignment.o
      alignment::alignmentPhylip_PamlToFile(std::ostream&) in alignment.o
      alignment::alignmentClustalToFile(std::ostream&) in alignment.o
      alignment::alignmentNexusToFile(std::ostream&) in alignment.o
      alignment::alignmentSummaryHTML(char*, int, int, int*, int*, float*) in alignment.o
      alignment::alignmentColourHTML(std::ostream&) in alignment.o
      ...
  "std::basic_ostream<char, std::char_traits<char> >& std::operator<<<char, std::char_traits<char>, std::allocator<char> >(std::basic_ostream<char, std::char_traits<char> >&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)", referenced from:
      alignment::fillMatrices(bool) in alignment.o
      alignment::getSequences(std::ostream&) in alignment.o
      alignment::alignmentPhylipToFile(std::ostream&) in alignment.o
      alignment::alignmentPhylip3_2ToFile(std::ostream&) in alignment.o
      alignment::alignmentPhylip_PamlToFile(std::ostream&) in alignment.o
      alignment::alignmentClustalToFile(std::ostream&) in alignment.o
      alignment::alignmentFastaToFile(std::ostream&) in alignment.o
      ...
  "std::basic_istream<char, std::char_traits<char> >& std::operator>><char, std::char_traits<char> >(std::basic_istream<char, std::char_traits<char> >&, char*)", referenced from:
      similarityMatrix::loadSimMatrix(char*) in similarityMatrix.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [readal] Error 1

**Comment by scapella** [comment]
dear @dinhe878 
I have been investigating a bit and would suggest to clean any intermediate file e.g. .o using **make clean** and then try to compile again again using **make**.

If that doesn't work, could you please compile a simple "Hello World" program for understanding what it may be missing?

```
#include <iostream>
#include <string>

int main() {
	std::string message = "Hello, world!";
    std::cout << message << std::endl;
}
```
using **gcc main.cpp -lstdc++ -o main.o**

**Comment by dinhe878** [comment]
Thanks @scapella and it worked after deleting all the .o files!
