### ISSUE TITLE
Compareset may crash when more alignments than sequences on the alignments are provided

### ISSUE THREAD

**Issue by Vicfero** [scapella/trimal#44]
This is due to this line: [compareFiles.cpp:56](https://github.com/scapella/trimal/blob/d3bc8bffd25b0618cb534b1266c1f20efd2a362f/source/compareFiles.cpp#L56)

Currently:   numResiduesAlig = new int[numSeqs];

Should be: numResiduesAlig = new int[numAlignments];

**Comment by scapella** [comment]
Duplicate of 45#
