### ISSUE TITLE
TrimAl compareset error

### ISSUE THREAD

**Issue by emaldo** [scapella/trimal#45]
Dear Salvador Capella-Gutiérrez and Toni Gabaldón,

I was testing trimAl with the -compareset option (employing a few nucleotide alignments with the same sequences across alignments in same order), but i got a few errors (please see in attachment). Am I missing something?
TrimAl was compiled from the latest version (v1.4.rev22 build[2015-05-21]) available in https://github.com/scapella/trimal.

Are these errors related to alignment differences? If not, is it possible that a future version can fix these?

Thanks for your attention.

Best regards,
Emanuel Maldonado.
CIIMAR, University of Porto. 

[trimal_compareset_error.txt](https://github.com/scapella/trimal/files/1834198/trimal_compareset_error.txt)
[msa.zip](https://github.com/scapella/trimal/files/1834201/msa.zip)

**Comment by scapella** [comment]
Commit https://github.com/scapella/trimal/commit/83256706100c06176f8a1b89b23d6425411c2df5 closes #45 #44
