### ISSUE TITLE
trimal -selectcols doesn't work

### ISSUE THREAD

**Issue by darap888** [scapella/trimal#56]
ERROR: Parameter "-selectcols" not valid.

I found somewhere pdf manual, where "select" is used instead - still the same error

**Comment by scapella** [comment]
Hi,

Could you please indicate the command-line used?

Thanks!

S

**Comment by darap888** [comment]
Thank you for response.

I tried several variations because I was not sure, how to use it

trimal -in t1.fas -out t2.fas -select {0-592,4268-5581}

and

 trimal -in t1.fas -out t2.fas -selectcols {0-592,4268-5581}

and without gap after option

 trimal -in t1.fas -out t2.fas -selectcols{0-592,4268-5581}

and with a gap after bracket

 trimal -in t1.fas -out t2.fas -selectcols { 0-592,4268-5581}

and without brackets at all

 trimal -in t1.fas -out t2.fas -selectcols 0-592,4268-5581


When I use option -noallgaps, it is working perfectly

Thnx in advance.

**Comment by scapella** [comment]
Could you please try out? trimal -in t1.fas -out t2.fas -selectcols { 0-592,4268-5581 }

As parsing arguments from command-line in C++ is difficult, we decided that the best way to do it is by asking for the opening bracket "{", blank space, all individual columns and/or intervals together separated either by "," and/or "-"; then blank space, and the closing bracket "}"

Hope it helps,

S

**Comment by darap888** [comment]
Actually, I tried it in the first place. It did not work.
In the end, I trimmed these columns with mothur pcr.seqs, as my colleague suggested (in case, anyone would need this function).

Anyway, I used trimal to delete all-gaps columns and it was good for my purpose. 

Thank you very much again.

**Comment by camilogarciabotero** [comment]
Hi @scapella,

I am also struggling with the `-selectcols` option. I've tried some of the variations with the "{}" symbols with space, without space, etc. However, when using it as the best way suggested e.g. `-selectcols { 0-2142,0-2142 }` (here I want to delete the first 2142 columns of my alignment), the problem continues. I could spot an error from my terminal (I'm using z-shell on OS X Catalina). 

![Screen Shot 2020-03-22 at 4 03 23 PM](https://user-images.githubusercontent.com/25586362/77260540-acc80b80-6c56-11ea-9b26-c17151a561c0.png)

I'm still stuck on this issue. So, if you can give me some lights on how to overcome it, I would really appreciate this.

Regards,
Camilo.

**Comment by nicodr97** [comment]
Hi @camilogarciabotero,

It seems that this is an issue with zsh parsing curly braces. You can either change to bash in your terminal or you can add a slash or single quotes to curly braces.
Option 1: `exec bash` to change current shell and use the following arguments `-selectcols { 0-2142,0-2142 }`
Option 2: execute it with zsh and  the following arguments `-selectcols \{ 0-2142,0-2142 \}` or  `-selectcols '{' 0-2142,0-2142 '}'`

As for what @darap888 commented,
Are you still having that error? Could specify which OS, shell and trimAl version are you using? What @scapella suggested should work fine (`trimal -in t1.fas -out t2.fas -selectcols { 0-592,4268-5581 }`).

Thank you for your feedback!
Nicolás
