### ISSUE TITLE
Compilation time and memory

### ISSUE THREAD

**Issue by BernardoBello** [scapella/trimal#6]
Hi,

While compilation, I had t stop because the make command was using all my system memory (12 GB). Is that normal? Below is where I had to stop the compilation process.

I'm running MACOSX Lion.

Thank you,
Bernardo

--------------------------------------------------------------------------------
dhcp-172-17-27-227:source bernardo$ make
g++ -Wall -O2  -c alignment.cpp rwAlignment.cpp autAlignment.cpp
g++ -Wall -O2  -c statisticsGaps.cpp
g++ -Wall -O2  -c utils.cpp
g++ -Wall -O2  -c similarityMatrix.cpp
g++ -Wall -O2  -c statisticsConservation.cpp
g++ -Wall -O2  -c sequencesMatrix.cpp
g++ -Wall -O2  -c compareFiles.cpp
g++ -Wall -O2  -o readal readAl.cpp -lm alignment.o statisticsGaps.o utils.o similarityMatrix.o statisticsConservation.o sequencesMatrix.o compareFiles.o
g++ -Wall -O2  -o trimal main.cpp -lm alignment.o statisticsGaps.o utils.o similarityMatrix.o statisticsConservation.o sequencesMatrix.o compareFiles.o

^Cmake: *** [trimal] Interrupt: 2

**Comment by scapella** [comment]
After some testing, I realized this problem seems to be related to the optimization (-O2 flag) so removing this from the makefile should make the job.
