### ISSUE TITLE
"Permission denied" when installing (MacOS M1 chip)

### ISSUE THREAD

**Issue by HeidiOttesen** [scapella/trimal#62]
Hey!

Sorry, new at this, need it for schoolwork.
I don't know if this is related to the new chip in macbooks but when I try to execute the makefile I get Permission denied.
```
    (base) ... source % make
    make: makefile: Permission denied
    make: *** No targets.  Stop.
```
I tried making the makefile executable
```
    (base) ... source % chmod a+x makefile
```
I also tried running the makefile
```
    (base) ... source % /Users/..../trimAl/source/makefile 
    zsh: permission denied: /Users/..../trimAl/source/makefile
```
Help please 0:)

**Comment by nicodr97** [comment]
Hi @HeidiOttesen,
Are you still having this problem? Could you try to compile it with root permissions (`sudo make`)?
