### ISSUE TITLE
Error: the symbol '*' is incorrect

### ISSUE THREAD

**Issue by Wuhl00** [scapella/trimal#70]
My fasta file ended up with ‘*’, so when I put my aligned file to trim I got this report. does it matter?

**Comment by nicodr97** [comment]
I am sorry @Wuhl00, the report you got is the name of the issue (Error: the symbol '*' is incorrect)? And what do you mean exactly with "My fasta file ended up with '\*' "? Do you mean the content of the file? Its name?

**Comment by Wuhl00** [comment]
Hi, sorry for replying so late.
"My fasta file ended up with ‘*’" which means my sequences end up with symbol ‘*’ because my fasta file was disposed by other software first. I think this did’t affect trimAl because I find it also worked ,and actually it was easy to remove ‘*’ by coding, which won’t show the error anymore.
Thank you for contacting ,all best to you ! 😊

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: Nicolás Díaz Roussel ***@***.***>
发送时间: Thursday, May 4, 2023 9:20:37 PM
收件人: inab/trimal ***@***.***>
抄送: Wuhl00 ***@***.***>; Mention ***@***.***>
主题: Re: [inab/trimal] Error: the symbol '*' is incorrect (Issue #70)


I am sorry @Wuhl00<https://github.com/Wuhl00>, I cannot see the report you got. And what do you mean exactly with "My fasta file ended up with ‘*’"? Do you mean the content of the file? Its name?

**Comment by sinamajidian** [comment]
when I use options `-strictplus` or `-strict`, I also get thousands of "Error: the symbol '?' is incorrect". 
```
trimal -in my_msa.phy -out my_msa_out.phy  -strictplus

```
My MSA sequence is like this 
```
$ head -n 3  my_msa.phy 
 230 133652
M6-4  ?????????? ?????????? ?????????? ?????????? ??????????
M6-3  ?????????? ?????????? ?????????? ?????????? ??????????
M5-1  ?????????? ?????????? ?????????? ?????????? ??????????

$ sed -n 200,203p my_msa.phy
C4-4  MDETTIDSIF AGSLK-SLPA VSSKIVRIFT SSTFTGTXXX XXXXXXXXXX
A3-3  MDETTIDSIF AGSLK-SLPA VSSKIVRIFT SSTFTGTXXX XXXXXXXXXX
C8-2  MDETTIDSIF AGSLK-SLPA VSSKIVRIFT XXXXXDTTME RNTLMAQCYP
```
But there is no error when I use `gappyout ` or `automated1 ` and the program finish successfully in a few seconds, generating a trimmed MSA. 
```
$ trimal -in my_msa.phy -out my_msa_out2.phy    -automated1
$ head -n 3 my_msa_out2.phy    
 230 103599
M6-4   ????????????????????????????????????????????????????????????
M6-3   ????????????????????????????????????????????????????????????
```

and this is my versions:
```
$ trimal --version
trimAl v1.4.rev15 build[2013-12-17]
$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Description:	Red Hat Enterprise Linux release 8.4 (Ootpa)
```

**Comment by nicodr97** [comment]
Hi @sinamajidian,

Currently there is no wildcard for unknown amino acids, so the programme will fail in some cases if a sequence has a symbol that is not an amino acid. As you experienced, gappyout will work ok because it does not use any similarity matrix as strict and strictplus do. For automated1 it will depend on the characteristics of the input MSA, since it selects between gappyout and strict at the end.

Thank you for your feedback!
