### ISSUE TITLE
Error message on alignment when using TrimAl

### ISSUE THREAD

**Issue by sakuragi0109** [scapella/trimal#74]
Hi everyone, 

I'm runing trimAl for my aligned amino acid sequences, and I get the error "Error: the symbol 'U' accesing the matrix is not defined in this object". 
I double checked and the U should be selenocysteine, so there mustn't be any mistake in the alignment file, I reckon. Is there anyone having any idea how to fix this problem? 

Thank you so much!

**Comment by nicodr97** [comment]
Hi @sakuragi0109,

trimAl default similarity matrix (BLOSUM62) is not considering U as a valid amino acid. You might replace U residues by other residue or you might use `-matrix` to pass a similarity matrix that includes that amino acid.
