### ISSUE TITLE
WARNING 010

### ISSUE THREAD

**Issue by WRran-Hydrogen** [scapella/trimal#76]
Hi guys,

I'm runing trimAl for my aligned amino acid sequences, but when I run the common command there is always a WARING 010 :
This is my command:
**trimal -in PF00905_test.afa -out alig.msa -automated1**

and the results in terminal:
**[WARNING 010] [fasta] -> To prevent overriding file alig.msa a suffix has been added. Final filename: alig.msa.0**

When I use multiple specifie formats to output, I will have the same problem. I don't want to have the suffix automatically added.
Does anyone have this problem?

trimAl version: 2.0

**Comment by nicodr97** [comment]
Hi @WRran-Hydrogen ,

Currently that is the automatic behaviour of the program when the output file already exists. We will add a parameter to allow overwriting.

**Comment by WRran-Hydrogen** [comment]
Thanks for your reply. Some problem were found in trimAl align algorithm between normal align and automated1.
The first command for **heuristic selection**: _trimal -in Integrase.afa -out Integrase.msa -automated1_
The next command for normal align: _trimal -in Integrase.afa -out Integrase.msa -gt 0.7_
After that, they show diffenent alignment results as follows:

> (-automated1)
>\>IMGVR_UViG_2974792740_000001
------G------------------
>\>IMGVR_UViG_3300029768_000208
------G------------------
>\>IMGVR_UViG_3300031555_010270
------G------------------
(-gt 0.7)
>\>IMGVR_UViG_2974792740_000001
MEYTYYVVD---QPEAIDL--YTEI*
>\>IMGVR_UViG_3300029768_000208
MGLLILKTT---QRQYLDY--NRPF*
>\>IMGVR_UViG_3300031555_010270
-----LKTA---QRQYIDY--NRPF*

so they get completely different results will affect the later building ML tree process by IQ-TREE.

Another question about amino acid fuzzy translations:

![image](https://github.com/inab/trimal/assets/117963364/de6efb6b-f920-4c89-92ff-8587e55c7ba4)

IMGVR_UViG_7000000289_000277
-----------X------------ (X is the result of fuzzy translation and does not represent any amino acid )
IQ-TREE program was terminated due to trimAl result problem

**Comment by nicodr97** [comment]
First of all, let me correct myself because I was not right about the current functioning of the `-out` parameter. It's adding the suffix in all case but that's solved in #80. As for your second comment, I don't really understand what your question is. Using `-automated1` will trim the MSA using a similarity or a gap method with a particular threshold depending on certain characteristics of the alignment. The parameter `-gt`, on the other hand, will trim based on the value you establish manually. It's completely normal that they don't generate the same MSA.

**Comment by WRran-Hydrogen** [comment]
I apologize for my unclear formulation of the second question, and I have carefully consulted the trimAl documentation:"**Automated trimming heuristic: automated1. (Optimized for Maximum Likelihood phylogenetic tree reconstruction).**"
![image](https://github.com/inab/trimal/assets/117963364/af49f0a7-98a9-45c4-9aa8-832cca0f0c46)
So I just don't know how to choose better parameters (_-automated1_ or _-gt custom Vakyes_)for the next work (This is my fault😢), because I found that the ML phylogenetic tree constructed using the results of _automated1_ is not completely plausible either, maybe using Bayesian tree building of the prior model will give better results, but keeping relatively more amino acid/nucleotide sites could get better mutation model features.
