### ISSUE TITLE
Removing short sequences

### ISSUE THREAD

**Issue by theo-allnutt-bioinformatics** [scapella/trimal#81]
I cannot find a way to remove sequences from an msa which fall below a length threshold. The alignment below is a small part of one after apply -gt 75 -resoverlap 0.90 -seqoverlap 0.90 and has a sequence with only 3 bp. I have tried -maxidentity but this seems difficult to tune so that it does not also remove longer sequences. Thanks for any suggestion.

>378044
ttttatgagtggaagaaagatggatccggaaaacagccttactacattcacttcaaagat
ggacgcccccttgtctttgctgctctttatgattcttggcaaaatgctgaaggt
>378018
ttttatgagtggaagaaagatggatccggaaaacagccttactacattcacttcaaagat
ggacgcccccttgtcttt------------------------------------
>377967
ttttatgagtggaagaaagatggatccggaaaacagccttactacattcacttcaaagat
ggacgcccccttgtctttgctgctctttatgattcttggcaaaattctgaaggt
>377964
ttttatgagtggaagaacgatggatccggaaaacagccttactacattcacttcaaagat
ggacgcccccttgtctttgctgctctttatgattcttggcaaaattctgaaggt
>377989
---tat------------------------------------------------------
------------------------------------------------------
>377958
ttttatgagtggaagaaagatggatccggaaagcagccttactacattcacctcaaagat
ggacgcccccttgtctttgctgctctttatgattcttggcaaaattctgaaggt
>377955
ttttatgagtggaagaaagatggatccggaaaacagccttactacattcacttcaaagat
ggacgcccccttgtctttgctgctctttatgattcttggcaaaattctgaaggt
>377984
ttttatgagtggaagaaagatggatccggaaaacagccttactacattcacttcaaagat
ggacgcccccttgtctttgctgctctttatgattcttggcaaaattctgaaggt
>378030
ttttatgactggaagaacgatggatccggaaaacagccttactacattcacttcaaagat
ggacgcccccttgtctttgctgctctttatgattcttggcaaaattctgaaggt
>377997
ttttatgagtggaagaaagatggatccagaaaacagccttactacattcacttcaaagat
ggacgccctcttgtttttgctgctctttatgattcttggcaaaattctgaaggt

**Comment by nicodr97** [comment]
Hi @theo-allnutt-bioinformatics ,

I think that a possible solution here is to increase the -seqoverlap value, although I am not sure which are the exact values you used since -gt should be between 0 and 1 and -seqoverlap may be between 0 and 100.

Let me know if this helps.

**Comment by theo-allnutt-bioinformatics** [comment]
ok, I see, I was using -gt 0.75 and -seqoverlap 0.9 -resoverlap 0.9, so had the values very wrong!
