### ISSUE TITLE
Cutting header name to 10 letters/symbols

### ISSUE THREAD

**Issue by sam-mick** [scapella/trimal#82]
Hi there,

I've noticed that the header names used for an aligned file are getting cut down to just 10 letters or symbols, e.g. THISISMYGENENAME -> THISISMYGE

I read about keepheader in old documentation / issues, but it seems to be missing from latest versions.

Is there any workaround for this?

Thanks.

**Comment by nicodr97** [comment]
Hi @samandmac,

Which version of trimAl are you using? In the current main version you should be able to run with the keepheader parameter. Could you write some lines of your input here?

Thank you

**Comment by sam-mick** [comment]
Hi @nicodr97,

Apologies, I was using 1.2 - the latest version from GitHub is working perfectly -  thank you very much!
