### ISSUE TITLE
errors of "Segmentation fault (core dumped)"

### ISSUE THREAD

**Issue by zhengyanstu** [scapella/trimal#93]
Dear developers:
I have already downloaded trimal-1.4.1, after compiling, whenever I run trimaI, I always encounter the error "Segmentation fault (core dumped)." How can I resolve this issue?

**Comment by nicodr97** [comment]
Hello @zhengyanstu,
I may help you with some additional information. Did you download this version by cloning it from this repository? What command are you running? What OS are you using?

**Comment by zhengyanstu** [comment]
Sorry for replying so late. I don't know why I didn't receive the message before. I download this version by cloning it from this repository. After reinstalling, the problem hasn't occurred for the time being. I will check again later, thank you for your reply.

> Hello @zhengyanstu, I may help you with some additional information. Did you download this version by cloning it from this repository? What command are you running? What OS are you using?
